wrapper:
  config_file_name: velodyne.yaml
  lidar_topic: /velodyne_points
  imu_topic: /handsfree/imu
  lidar_type: 1 # 0)avia 1) velodyne

map:
  type: ikdtree
  map_side_length_2: 500
  map_resolution: 0.5
  ikdtree_delete_criterion: 0.5
  ikdtree_balance_criterion: 0.7
  ikdtree_downsample_size: 0.5

front_end:
  extrin_r: [1,0,0,
            0,1,0,
            0,0,1]
  extrin_t: [-0.27255, 0.00053,-0.17954]
  enable_record: true
  record_file_name: m2dgr_street05.txt
ieskf:
  cov_gyroscope: 0.1
  cov_acceleration: 0.1
  cov_bias_acceleration: 0.0001
  cov_bias_gyroscope: 0.0001

back_end:
  keyframe_translation_thresh: 1.0
  keyframe_rotation_thresh_deg: 10.0
  force_keyframe_every_n: 30
  keyframe_voxel_leaf_size: 0.5
  map_voxel_leaf_size: 0.5
  odom_translation_information: 100.0
  odom_rotation_information: 150.0
  icp_max_iterations: 30
  icp_max_correspondence_distance: 15.0
  icp_fitness_threshold: 1.5
  loop_translation_information: 30.0
  loop_rotation_information: 50.0
  optimizer_max_iterations: 15
  optimizer_stop_delta_norm: 0.0001
  optimizer_damping_lambda: 0.000001
